name: flutter_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  intl: ^0.20.1
  flutter_reorderable_grid_view: ^5.4.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
